name: scheduled-publish

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  add-blog-and-publish:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Show pwd
        run: pwd

      - name: Set OpenAI API key as env var
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: echo "API keys set successfully"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: latest

      - name: Checkout ecrivai-blog-hugo with submodules
        uses: actions/checkout@v3
        with:
          repository: ruankie/ecrivai-blog-hugo
          # path: ecrivai-blog-hugo
          submodules: true
      
      - name: Go to root
        run: |
          cd ..
          pwd

      - name: Checkout ecrivai
        uses: actions/checkout@v3
        with:
          repository: ruankie/ecrivai
          # path: ecrivai
        
      - name: Go to root
        run: |
          cd ..
          pwd

      - name: Inspect dir tree
        run: tree -L 2

      - name: Go to ecrivai repo
        run: cd ecrivai

      - name: Setup and activate conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ecrivai
          environment-file: conda.yml

      - name: Create blog post
        run: python ecrivai/add_blog.py --out-dir "../ecrivai-blog-hugo/content/posts"

      - name: Go to ecrivai-blog-hugo repo
        run: cd ../ecrivai-blog-hugo

      - name: Rebuild static site with Hugo
        run: hugo -d docs

      - name: Commit and push changes to ecrivai-blog-hugo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto add blog post
          repository: .
          #branch: main